# Generated by Django 5.2.5 on 2025-08-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
